GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: 

{
    "title": "blog list 3",
    "author": "prueba 3",
    "url": "www.prueba3.com",
    "userId": "65d69ff659d382a71e971f56"
}
